### ISSUE TITLE
MarksLib compilation error (-2741)

### ISSUE THREAD

**Issue by collacocca** [alldritt/AppleScriptLibraries#1]
Using the curl link -
'curl https://raw.githubusercontent.com/alldritt/AppleScriptLibraries/master/MarksLib.applescript | osacompile -o ~/Library/Script\ Libraries/MarksLib.scpt'
results in -
'compilation error: Expected class name but found application constant or consideration. (-2741)'

**Comment by alldritt** [comment]
I'm not able to reproduce the problem you experienced here on my Monterey system.  Here's what I see when I run the installation command:

```
mall@mark build % curl https://raw.githubusercontent.com/alldritt/AppleScriptLibraries/master/MarksLib.applescript | osacompile -o ~/Library/Script\ Libraries/MarksLib.scpt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6148  100  6148    0     0  67444      0 --:--:-- --:--:-- --:--:-- 72329
mall@mark build % 
```

Please try again.  If the problem persists, please give more details of the system your are using.

**Comment by collacocca** [comment]
Hi Mark,
Thanks for the quick reply. Here what I see -
![marksLib_03](https://user-images.githubusercontent.com/16597614/218299585-95ad801d-ca9e-43a8-bc25-368c4755a6f6.jpg)
Everything else here is standard, nothing unusual - MacBookPro/Mojave 14.6.
TYIA - Peter

**Comment by collacocca** [comment]
Hi Mark,
sorry for wasting your time, found the mistake: a XML-Lib in the wrong place caused the trouble.
Everything good now
Thank you - Peter
